Repository googleapis/java-dlp, pull requests merged in 2020-09, with the labels that each got.

#264 fix: flaky testInspectStringMultipleRulesPatientRule
  samples/snippets/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#266 docs: expand parent field format, and BigQuery sampling options. Also describing which transformations are allowed for ReidentifyContent API calls, and the custom alphabet allowed for format-preserving encryption (FPE).
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/BigQueryOptions.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDeidentifyTemplateRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDeidentifyTemplateRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDlpJobRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDlpJobRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateInspectTemplateRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateInspectTemplateRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateJobTriggerRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateJobTriggerRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateStoredInfoTypeRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateStoredInfoTypeRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CryptoReplaceFfxFpeConfig.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CryptoReplaceFfxFpeConfigOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DeidentifyContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DeidentifyContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InfoType.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InfoTypeOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDeidentifyTemplatesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDeidentifyTemplatesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInfoTypesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInfoTypesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInspectTemplatesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInspectTemplatesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListStoredInfoTypesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListStoredInfoTypesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RedactImageRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RedactImageRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ReidentifyContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ReidentifyContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#271 samples: bring back samples README
  samples/snippets/README.md
Labels: api: dlp, cla: yes, samples

#272 chore: regenerate README
  README.md
  synth.metadata
Labels: api: dlp, cla: yes, context: none

#274 docs: correct the links for parent fields
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDeidentifyTemplateRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDeidentifyTemplateRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDlpJobRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateDlpJobRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateInspectTemplateRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateInspectTemplateRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateJobTriggerRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateJobTriggerRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateStoredInfoTypeRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CreateStoredInfoTypeRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DeidentifyContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DeidentifyContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDeidentifyTemplatesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDeidentifyTemplatesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInspectTemplatesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListInspectTemplatesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListStoredInfoTypesRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListStoredInfoTypesRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RedactImageRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RedactImageRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ReidentifyContentRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ReidentifyContentRequestOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: partial

#277 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#278 fix: flakey snippets RiskAnalysisTests#testLDiversity test + Dlp samples format's
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableBucketing.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableConditionInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableConditionMasking.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableRowSuppress.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyTableWithFpe.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyWithInfoType.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyWithRedaction.java
  samples/snippets/src/main/java/dlp/snippets/DeIdentifyWithReplacement.java
  samples/snippets/src/main/java/dlp/snippets/InspectBigQueryTable.java
  samples/snippets/src/main/java/dlp/snippets/InspectBigQueryTableWithSampling.java
  samples/snippets/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  samples/snippets/src/main/java/dlp/snippets/InspectGcsFile.java
  samples/snippets/src/main/java/dlp/snippets/InspectImageFile.java
  samples/snippets/src/main/java/dlp/snippets/InspectImageFileAllInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/InspectImageFileListedInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/InspectPhoneNumber.java
  samples/snippets/src/main/java/dlp/snippets/InspectString.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringCustomHotword.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
  samples/snippets/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
  samples/snippets/src/main/java/dlp/snippets/InspectTable.java
  samples/snippets/src/main/java/dlp/snippets/InspectTextFile.java
  samples/snippets/src/main/java/dlp/snippets/InspectWithCustomRegex.java
  samples/snippets/src/main/java/dlp/snippets/ReIdentifyTableWithFpe.java
  samples/snippets/src/main/java/dlp/snippets/RedactImageFile.java
  samples/snippets/src/main/java/dlp/snippets/RedactImageFileColoredInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/RedactImageFileListedInfoTypes.java
  samples/snippets/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  samples/snippets/src/test/java/dlp/snippets/DeIdentificationTests.java
  samples/snippets/src/test/java/dlp/snippets/InspectTests.java
  samples/snippets/src/test/java/dlp/snippets/RedactTests.java
  samples/snippets/src/test/java/dlp/snippets/RiskAnalysisTests.java
  samples/snippets/src/test/java/dlp/snippets/TestBase.java
Labels: api: dlp, cla: yes, samples

#288 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: dlp, automerge, cla: yes

#289 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#293 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
