Repository googleapis/java-dlp, pull requests merged in 2020-06, with the labels that each got.

#189 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#193 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#195 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#197 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#207 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#212 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-dlp/pom.xml
  grpc-google-cloud-dlp-v2/pom.xml
  pom.xml
  proto-google-cloud-dlp-v2/pom.xml
Labels: cla: yes

#213 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#226 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
