Repository googleapis/java-dlp, pull requests merged in 2021-09, with the labels that each got.

#648 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: dlp, automerge, context: full

#649 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dlp, automerge

#651 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: dlp, automerge, context: full

#657 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dlp, automerge

#661 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: dlp, automerge

#683 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: dlp, automerge
