Repository googleapis/java-dlp, pull requests merged in 2021-02, with the labels that each got.

#410 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#414 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#420 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#421 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#419 docs: generate sample code in the Java microgenerator
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/package-info.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full, samples

#427 chore: update gapic-generator-java to 0.0.20
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/GrpcDlpServiceStub.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/DlpServiceClientTest.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/MockDlpServiceImpl.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#428 chore: Re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dlp, cla: yes, context: full

#426 chore: update javadoc plugin config link
  pom.xml
Labels: api: dlp, cla: yes

#429 build: reduce download junk in log files
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#431 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/gapic_metadata.json
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#434 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#435 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#437 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#446 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes
