Repository googleapis/java-dlp, pull requests merged in 2021-03, with the labels that each got.

#448 feat(generator): update protoc to v3.15.3
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CharsToIgnore.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CharsToIgnoreOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ContentItem.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ContentItemOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CryptoReplaceFfxFpeConfig.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CryptoReplaceFfxFpeConfigOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CustomInfoType.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/Key.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/PrivacyMetric.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/QuasiId.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/QuasiIdOrBuilder.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RedactImageRequest.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/Value.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ValueOrBuilder.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#450 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#451 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#453 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#454 chore(release): update Java microgenerator to 1.0.1
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceSettings.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/package-info.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/DlpServiceStub.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/DlpServiceStubSettings.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/GrpcDlpServiceCallableFactory.java
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/GrpcDlpServiceStub.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/DlpServiceClientTest.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/MockDlpService.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/MockDlpServiceImpl.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DeidentifyTemplateName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpContentName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpJobName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/FindingName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectTemplateName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/JobTriggerName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/LocationName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/OrganizationLocationName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/OrganizationName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ProjectName.java
  proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/StoredInfoTypeName.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#456 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#458 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#459 chore: update gax-java dependency to 1.62
  grpc-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpServiceGrpc.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#462 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#465 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/MockDlpServiceImpl.java
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full, samples

#466 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#469 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#471 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#472 docs: version update
  README.md
Labels: api: dlp, cla: yes

#474 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dlp, automerge, cla: yes

#477 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dlp, cla: yes, context: full
